FROM vs2015

ADD cmake-3.12.1-win64-x64.tar.gz .
#ADD jre-8u181-windows-x64.tar.gz .
ADD ninja.exe .
RUN setx path "C:\\cmake-3.12.1-win64-x64\\bin;%PATH%"

COPY opencv-2.4.13.6.zip .
RUN cmake -E tar -xzf opencv-2.4.13.6.zip

WORKDIR C:\\opencv-2.4.13.6\\build

RUN C:\BuildTools\VC\Auxiliary\Build\vcvarsall.bat x86 -vcvars_ver=14.0 && cmake -DCMAKE_BUILD_TYPE=Release -GNinja .. && ninja